apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- service-monitor.yaml
images:
- name: alisongabiatti/sli-services-exporter
  newTag: 1.0.4
