apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sli-services-exporter
  namespace: monit
spec:
  endpoints:
  - interval: 30s
    port: metrics
    path: /
  namespaceSelector:
    matchNames:
      - monit
  selector:
    matchLabels:
      app: sli-services-exporter